name: Bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-
      
    - name: deps
      run: |
           sudo apt-get install -y libaio-dev libgtest-dev libgmock-dev

    - name: Install LLVM 18
      run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install clang-tools-18
    - name: Remove old LLVM
      run: |
        sudo rm -rf /usr/bin/clang++ /usr/bin/clang
        sudo rm -rf /usr/bin/clang-scan-deps
        sudo ln -s /usr/bin/clang-scan-deps-18 /usr/bin/clang-scan-deps
    - name: Remove GCC 12
      run: |
        sudo apt-get remove gcc-12 -y
        sudo rm -rf /usr/lib/gcc/x86_64-linux-gnu/12
    - name: Remove old bazel
      run: |
        sudo rm -rf `which bazel`

    - name: Use LLVM 18
      run: |
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
        sudo update-alternatives --install /usr/bin/clang-scan-deps clang-scan-deps /usr/bin/clang-scan-deps-18 100
        sudo update-alternatives --config cc
    - name: Check Clang 18
      run: clang-18 -v

    - name: Download prebuilt bazel
      run: |
        wget https://github.com/PikachuHyA/async_simple/releases/download/bazel/bazel
        chmod +x bazel
        sudo cp bazel /usr/bin
      working-directory: ${{github.workspace}}

    - name: Build unit_test
      working-directory: ${{github.workspace}}
      run: ./bazel build --action_env=CC=/usr/bin/clang-18 unit_test/...

    - name: Test unit_test
      working-directory: ${{github.workspace}}
      run: ./bazel test --action_env=CC=/usr/bin/clang-18 --test_output=errors unit_test/...

    - name: Test integration_test
      working-directory: ${{github.workspace}}/integration_test
      run: bash test_all.sh
